---
abstract: "Toolforge Mix'n'match tool app."
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Toolforge-MixNMatch
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Error::Pure: 0.15
  Getopt::Std: 0
  IO::Barf: 0
  JSON::XS: 0
  LWP::Simple: 0
  LWP::UserAgent::https: 0
  Perl6::Slurp: 0
  Readonly: 0
  Toolforge::MixNMatch::Diff: 0.01
  Toolforge::MixNMatch::Object: 0.02
  Toolforge::MixNMatch::Print: 0.02
  Toolforge::MixNMatch::Struct: 0.02
  Unicode::UTF8: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/App-Toolforge-MixNMatch/issues
  homepage: https://github.com/michal-josef-spacek/App-Toolforge-MixNMatch
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/App-Toolforge-MixNMatch
version: '0.04'
